from __future__ import annotations

from typing import Final

StringAliases = tuple[str, ...]

_BASE_KNOWLEDGE_CODES: Final[dict[int, StringAliases]] = {
    1: ("rider",),
    2: ("teamster",),
    3: ("trainer",),
    4: ("acv",),
    5: ("automotive",),
    6: ("grav",),
    7: ("legged",),
    8: ("mole",),
    9: ("tracked",),
    10: ("wheeled",),
    11: ("jump drives",),
    12: ("life support", "life-support"),
    13: ("maneuver drive",),
    14: ("power systems",),
    15: ("battle dress",),
    16: ("beams",),
    17: ("blades",),
    18: ("exotics",),
    19: ("slug throwers",),
    20: ("sprays",),
    21: ("unarmed",),
    22: ("aeronautics",),
    23: ("flapper",),
    24: ("grav",),
    25: ("lta",),
    26: ("rotor",),
    27: ("winged",),
    28: ("bay weapons",),
    29: ("ortillery",),
    30: ("screens",),
    31: ("spines",),
    32: ("turrets",),
    33: ("artillery",),
    34: ("launcher",),
    35: ("ordnance",),
    36: ("wmd",),
    37: ("small craft",),
    38: ("spacecraft acs", "acs"),
    39: ("spacecraft bcs", "bcs"),
    40: ("aquanautics",),
    41: ("grav",),
    42: ("boat",),
    43: ("ship",),
    44: ("sub",),
    45: ("archeology",),
    46: ("biology",),
    47: ("chemistry",),
    48: ("history",),
    49: ("linguistics",),
    50: ("philosophy",),
    51: ("physics",),
    52: ("planetology",),
    53: ("psionicology",),
    54: ("psychohistory",),
    55: ("psychology",),
    56: ("robotics",),
    57: ("sophontology",),
    58: ("career: academia",),
    59: ("career: army",),
    60: ("career: navy",),
    61: ("career: <name>",),
    62: ("world: capital",),
    63: ("world: regina",),
    64: ("world: <name>",),
    65: ("culture: <name>",),
    66: ("language: <name>",),
}

KnowledgeCode = int
AssociatedSkillCodes = tuple[int, ...]
_DEFAULT_KNOWLEDGE_TO_SKILLS_ASSOCIATIONS: Final[dict[KnowledgeCode, AssociatedSkillCodes]] = {

    1: (),
    2: (),
    3: (),
    4: (),
    5: (),
    6: (),
    7: (),
    8: (),
    9: (),
    10: (),
    11: (),
    12: (),
    13: (),
    14: (),
    15: (),
    16: (),
    17: (),
    18: (),
    19: (),
    20: (),
    21: (),
    22: (),
    23: (),
    24: (),
    25: (),
    26: (),
    27: (),
}